--1. 請列出每個使用者每年借書數量，並依使用者編號和年度做排序 

SELECT M.USER_ID AS KEEPER_ID,  
	   M.USER_CNAME AS CNAME,
	   M.USER_ENAME AS ENAME,
	   YEAR(B.LEND_DATE) AS BORROWYEAR,
	   COUNT(B.LEND_DATE) AS BORROWCNT  
FROM MEMBER_M AS M
LEFT JOIN  BOOK_LEND_RECORD AS B ON M.USER_ID=B.KEEPER_ID
GROUP BY B.KEEPER_ID,M.USER_CNAME,M.USER_ENAME, YEAR(B.LEND_DATE),M.USER_ID
ORDER BY KEEPER_ID
