--9.新增一筆借閱紀錄，借書人為李四，書本ID為2294，借閱日期為2021/01/01，並更新書籍主檔的狀態為已借出且借閱人為李四  

INSERT INTO BOOK_LEND_RECORD ([BOOK_ID],[KEEPER_ID],[LEND_DATE]) 
SELECT 2294 AS BOOK_ID, '0002' AS KEEPER_ID, '2021/01/01' AS LEND_DATE  --, CRE_DATE, CRE_USR, MOD_DATE, MOD_USR
Values (2294,'0002',CONVERT(DATETIME,'2021/01/01'))

UPDATE BOOK_DATA
   SET BOOK_STATUS='B'
   WHERE BOOK_ID=2294 AND BOOK_KEEPER='李四' 

--對的
SELECT bd.BOOK_ID AS '書本ID',
	   CONVERT(VARCHAR,  bd.BOOK_BOUGHT_DATE, 111)  AS '購書日期',
	   CONVERT(varchar,  blr.LEND_DATE, 111)  AS '借閱日期',
	   CONCAT(bd.BOOK_STATUS,'-已借出') AS '狀態',
	   bc.BOOK_CLASS_NAME AS '書籍類別',
	   bd.BOOK_AMOUNT AS '購書金額',
	   m.USER_cNAME AS '借閱人'
FROM BOOK_DATA AS bd 
INNER JOIN BOOK_LEND_RECORD AS blr ON bd.BOOK_ID = blr.BOOK_ID 
INNER JOIN MEMBER_M AS M ON M.USER_ID=blr.KEEPER_ID
INNER JOIN BOOK_CLASS AS bc ON bc.BOOK_CLASS_ID=bd.BOOK_CLASS_ID
WHERE blr.KEEPER_ID='0002'

--10 借書人為李四，書本ID為2294，借閱日期為2021/01/01
DELETE FROM BOOK_LEND_RECORD 
WHERE BOOK_ID=2294 AND KEEPER_ID='0002'

/*
SELECT * FROM BOOK_LEND_RECORD WHERE BOOK_ID=2294
SELECT * FROM BOOK_DATA WHERE BOOK_KEEPER='李四' 
SELECT * FROM MEMBER_M m WHERE m.USER_CNAME='李四' 
*/



/*
--錯誤
SELECT bd.BOOK_ID AS '書本ID',
	   CONVERT(VARCHAR,  bd.BOOK_BOUGHT_DATE, 111)  AS '購書日期',
	   CONVERT(varchar,  blr.LEND_DATE, 111)  AS '借閱日期',
	   bd.BOOK_STATUS,
	   bc.BOOK_CLASS_NAME AS '書籍類別',
	   bd.BOOK_AMOUNT AS '購書金額',
	   m.USER_cNAME
FROM BOOK_LEND_RECORD blr 
INNER JOIN BOOK_DATA bd ON blr.BOOK_ID = bd.BOOK_ID
INNER JOIN MEMBER_M M ON bd.BOOK_KEEPER=m.USER_ID
INNER JOIN BOOK_CLASS bc ON bd.BOOK_CLASS_ID = bc.BOOK_CLASS_ID
WHERE bd.BOOK_ID=2294