--把2016,2017,2018,2019每年的資料分別查詢出來，和book class合併,
SELECT aaa.BOOK_CLASS_ID AS Class_ID,
	   aaa.BOOK_CLASS_NAME AS ClassName,
	   ISNULL(aaa.cnt2016,0)AS CNT2016,  --handle null
	   ISNULL(aaa.cnt2017,0)AS CNT2017,
	   ISNULL(aaa.cnt2018,0)AS CNT2018,
	   ISNULL(aaa.cnt2019,0)AS CNT2019 
FROM(
	SELECT bc.BOOK_CLASS_ID,bc.BOOK_CLASS_NAME,b.cnt2016,c.cnt2017 ,d.cnt2018,e.cnt2019  
	FROM BOOK_CLASS AS bc
	LEFT JOIN (
		SELECT bc.BOOK_CLASS_ID,bc.BOOK_CLASS_NAME,COUNT(bc.BOOK_CLASS_ID) AS cnt2016     --2016年資料 ,放類別的每年借閱數量
		FROM BOOK_LEND_RECORD AS blr 
		INNER JOIN BOOK_DATA AS bd ON blr.BOOK_ID = bd.BOOK_ID 
		INNER JOIN BOOK_CLASS AS bc ON bd.BOOK_CLASS_ID = bc.BOOK_CLASS_ID
		WHERE blr.LEND_DATE BETWEEN '2016/01/01' AND '2016/12/31' 
		GROUP BY bc.BOOK_CLASS_ID,bc.BOOK_CLASS_NAME
	) AS b ON bc.BOOK_CLASS_ID =b.booK_class_id
	LEFT JOIN(
		SELECT bc.BOOK_CLASS_ID,bc.BOOK_CLASS_NAME,COUNT(bc.BOOK_CLASS_ID) AS cnt2017 --2017年資料
		FROM BOOK_LEND_RECORD AS blr
		INNER JOIN BOOK_DATA AS bd ON blr.BOOK_ID = bd.BOOK_ID
		INNER JOIN BOOK_CLASS AS bc ON bd.BOOK_CLASS_ID = bc.BOOK_CLASS_ID
		WHERE blr.LEND_DATE BETWEEN '2017/01/01' AND '2017/12/31'
		GROUP BY bc.BOOK_CLASS_ID,bc.BOOK_CLASS_NAME
	)AS c ON bc.BOOK_CLASS_ID=c.BOOK_CLASS_ID
	LEFT JOIN(
		SELECT bc.BOOK_CLASS_ID,bc.BOOK_CLASS_NAME,COUNT(bc.BOOK_CLASS_ID) AS cnt2018  --2018年資料
		FROM BOOK_LEND_RECORD AS blr
		INNER JOIN BOOK_DATA AS bd ON blr.BOOK_ID = bd.BOOK_ID
		INNER JOIN BOOK_CLASS AS bc ON bd.BOOK_CLASS_ID = bc.BOOK_CLASS_ID
		WHERE blr.LEND_DATE BETWEEN '2018/01/01' AND '2018/12/31'
		GROUP BY bc.BOOK_CLASS_ID,bc.BOOK_CLASS_NAME
	)AS d ON bc.BOOK_CLASS_ID=d.BOOK_CLASS_ID
	LEFT JOIN(
		SELECT bc.BOOK_CLASS_ID,bc.BOOK_CLASS_NAME,COUNT(bc.BOOK_CLASS_ID) AS cnt2019   --2019年資料
		FROM BOOK_LEND_RECORD AS blr
		INNER JOIN BOOK_DATA AS bd ON blr.BOOK_ID = bd.BOOK_ID
		INNER JOIN BOOK_CLASS AS bc ON bd.BOOK_CLASS_ID = bc.BOOK_CLASS_ID
		WHERE blr.LEND_DATE BETWEEN '2019/01/01' AND '2019/12/31'
		GROUP BY bc.BOOK_CLASS_ID,bc.BOOK_CLASS_NAME
	)AS e ON bc.BOOK_CLASS_ID=e.BOOK_CLASS_ID
)AS aaa



















-------------------------------------------------------------------------------------------------
--未handle null
SELECT bc.BOOK_CLASS_ID,bc.BOOK_CLASS_NAME,b.cnt2016,c.cnt2017 ,d.cnt2018,e.cnt2019  FROM BOOK_CLASS AS bc
LEFT JOIN (
	SELECT bc.BOOK_CLASS_ID,bc.BOOK_CLASS_NAME,COUNT(bc.BOOK_CLASS_ID) AS cnt2016
	FROM BOOK_LEND_RECORD AS blr 
		JOIN BOOK_DATA AS bd ON blr.BOOK_ID = bd.BOOK_ID 
		JOIN BOOK_CLASS AS bc ON bd.BOOK_CLASS_ID = bc.BOOK_CLASS_ID
	WHERE blr.LEND_DATE BETWEEN '2016/01/01' AND '2016/12/31' 
	GROUP BY bc.BOOK_CLASS_ID,bc.BOOK_CLASS_NAME
) AS b ON bc.BOOK_CLASS_ID =b.booK_class_id
LEFT JOIN(
	SELECT bc.BOOK_CLASS_ID,bc.BOOK_CLASS_NAME,COUNT(bc.BOOK_CLASS_ID) AS cnt2017
	FROM BOOK_LEND_RECORD blr
	JOIN BOOK_DATA bd
	ON blr.BOOK_ID = bd.BOOK_ID
	JOIN BOOK_CLASS bc
	ON bd.BOOK_CLASS_ID = bc.BOOK_CLASS_ID
	WHERE blr.LEND_DATE BETWEEN '2017/01/01' AND '2017/12/31'
	GROUP BY bc.BOOK_CLASS_ID,bc.BOOK_CLASS_NAME
)AS c
ON bc.BOOK_CLASS_ID=c.BOOK_CLASS_ID
LEFT JOIN(
	SELECT bc.BOOK_CLASS_ID,bc.BOOK_CLASS_NAME,COUNT(bc.BOOK_CLASS_ID) AS cnt2018
	FROM BOOK_LEND_RECORD blr
	JOIN BOOK_DATA bd
	ON blr.BOOK_ID = bd.BOOK_ID
	JOIN BOOK_CLASS bc
	ON bd.BOOK_CLASS_ID = bc.BOOK_CLASS_ID
	WHERE blr.LEND_DATE BETWEEN '2018/01/01' AND '2018/12/31'
	GROUP BY bc.BOOK_CLASS_ID,bc.BOOK_CLASS_NAME
)AS d
ON bc.BOOK_CLASS_ID=d.BOOK_CLASS_ID
LEFT JOIN(
	SELECT bc.BOOK_CLASS_ID,bc.BOOK_CLASS_NAME,COUNT(bc.BOOK_CLASS_ID) AS cnt2019
	FROM BOOK_LEND_RECORD blr
	JOIN BOOK_DATA bd
	ON blr.BOOK_ID = bd.BOOK_ID
	JOIN BOOK_CLASS bc
	ON bd.BOOK_CLASS_ID = bc.BOOK_CLASS_ID
	WHERE blr.LEND_DATE BETWEEN '2019/01/01' AND '2019/12/31'
	GROUP BY bc.BOOK_CLASS_ID,bc.BOOK_CLASS_NAME
)AS e
ON bc.BOOK_CLASS_ID=e.BOOK_CLASS_ID
ORDER BY bc.BOOK_CLASS_ID



--取單一年度
SELECT bc.BOOK_CLASS_ID,bc.BOOK_CLASS_NAME,COUNT(bc.BOOK_CLASS_ID) AS cnt
	FROM BOOK_LEND_RECORD blr
	JOIN BOOK_DATA bd
	ON blr.BOOK_ID = bd.BOOK_ID
	JOIN BOOK_CLASS bc
	ON bd.BOOK_CLASS_ID = bc.BOOK_CLASS_ID
	WHERE blr.LEND_DATE BETWEEN '2017/01/01' AND '2017/12/31'
	GROUP BY bc.BOOK_CLASS_ID,bc.BOOK_CLASS_NAME
	


--寫錯的
	SELECT bcl.BOOK_CLASS_ID,bcl.BOOK_CLASS_NAME,
	--CASE WHEN YEAR(LEND_DATE)='2016' then 1 else 0 END AS 'a',
	--CASE WHEN YEAR(LEND_DATE)='2017' then 1 else 0 END AS 'b',
--CASE WHEN YEAR(LEND_DATE)='2018' then 1 else 0 END AS 'b',
--CASE WHEN YEAR(LEND_DATE)='2019' then 1 else 0 END AS 'd',
SUM() OVER (PARTITION BY bcl.BOOK_CLASS_ID)
FROM BOOK_LEND_RECORD blr
INNER JOIN BOOK_DATA bd
ON blr.BOOK_ID = bd.BOOK_ID
INNER JOIN BOOK_CLASS bcl
ON bd.BOOK_CLASS_ID = bcl.BOOK_CLASS_ID


	